server:
  port: 8001


spring:
  application:
    name: cloud-pament-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.129:3306/test?useUnicode=true&charcterEncoding=utf-8&useSSL=false
    username: root
    password: 126917

mybatis:
  mapperlocations: classPath/mapping/*.xml
  type-aliases-package: com.atguigu.db.entity
  configuration:
    map-underscore-to-camel-case: true

